### PR TITLE
fix: add trim modifier to text input (closes #220)

### LINKED ISSUE #220: Strip leading/trailing empty spaces
### Problem
Not stripped input values trigger a very cryptic error:

```
body,attributes,0,name: Attribute name must be a valid Python identifier and must not start/end with underscore
```

### Expectation
Trailing/leading spaces left in an input by accident should be stripped during the data validation.

### PR DESCRIPTION
**Pull request by jonas-brr**

### CODE REVIEW

File: frontend/src/components/inputs/TextInput.vue [hunk 1]
```diff
@@ -1,35 +1,44 @@
...
-    onInput(event) {
-      this.$emit("update:modelValue", event.target.value);
-    },
-  },
-};
+const modelValue = defineModel({ required: true });
+
+const props = defineProps([
+  "label",
+  "string",
```
Comment (TeodoraPavlova) [inline frontend/src/components/inputs/TextInput.vue:34]: Maybe a stupid question, but what is "string" used for?

File: backend/tests/conftest.py [hunk 2]
```diff
@@ -350,7 +350,7 @@ def delete(self, url, *, params=None, headers=None, cookies=None, auth=USE_CLIEN
             headers=headers,
             cookies=cookies,
             auth=auth,
-            follow_redirects=self._choose_redirect_arg(follow_redirects, allow_redirects),
+            follow_redirects=False,
```
Comment (TeodoraPavlova) [inline backend/tests/conftest.py:353]: Sorry, maybe I need a bit of a background here, why this is changed?

File: .github/workflows/default.yml [hunk 3]
```diff
@@ -22,7 +22,7 @@ jobs:
         with:
           python-version: "3.10"
       - name: Cache pip
-        uses: actions/cache@v2
+        uses: actions/cache@v4
```
Comment (TeodoraPavlova) [inline .github/workflows/default.yml:25]: I won't mind updating these in this MR, but generally, I would prefer doing this in a separate one.

Comment (jonas-brr) [reply .github/workflows/default.yml:25]: yeah.. I just wanted to see if that solves it, and it did.. Since it's a one liner I kept it.

File: backend/tests/conftest.py (hunk 2 above)
Comment (jonas-brr) [reply backend/tests/conftest.py:353]: That's some redirect logic magic for the custom test client (only there so we can send deletes with `json`). As the client changes this custom one gets broken. This time it is the `_choose_redirect_arg` method - it got removed from the base starlette test client.

Since we don't care about redirects in our tests, I just removed it.

File: frontend/src/components/inputs/TextInput.vue (hunk 1 above)
Comment (jonas-brr) [reply frontend/src/components/inputs/TextInput.vue:34]: tbf, I have no idea :smile: I just rewrote it to composition API as-is.

Comment (jonas-brr) [reply frontend/src/components/inputs/TextInput.vue:34]: but yes, bad name for a prop imho...

File: .github/workflows/default.yml (hunk 3 above)
Comment (jonas-brr) [reply .github/workflows/default.yml:25]: https://github.com/SUSE/aimaas/pull/223

File: frontend/src/components/inputs/TextInput.vue (hunk 1 above)
Comment (TeodoraPavlova) [reply frontend/src/components/inputs/TextInput.vue:34]: but the string prop is added by you? :laughing:

File: backend/tests/conftest.py (hunk 2 above)
Comment (TeodoraPavlova) [reply backend/tests/conftest.py:353]: Ok, thanks for the info

File: .github/workflows/default.yml (hunk 3 above)
Comment (TeodoraPavlova) [reply .github/workflows/default.yml:25]: ok, thanks

File: frontend/src/components/inputs/TextInput.vue (hunk 1 above)
Comment (jonas-brr) [reply frontend/src/components/inputs/TextInput.vue:34]: really?? Oh.. it must be some garbage from the types I added on autopilot and then realized the codebase is not typed..

Comment (jonas-brr) [reply frontend/src/components/inputs/TextInput.vue]: damn.. well spotted, thanks!

Comment (TeodoraPavlova) [reply frontend/src/components/inputs/TextInput.vue]: no worries :beers:

**Review by TeodoraPavlova — APPROVED** [review]
