### PR TITLE
fix: increase description length 1000 chars (closes #219)

### LINKED ISSUE #219: Increase the description max length
Description of an attribute is capped to `128` characters. That seems like  very little given descriptions can get very descriptive.

### PR DESCRIPTION
**Pull request by jonas-brr**

### CODE REVIEW

File: frontend/src/components/inputs/TextareaInput.vue [hunk 1]
```diff
@@ -1,26 +1,52 @@
 <template>
-  <BaseInput :label="label" :args="args" :vertical="vertical" :required="required">
+  <BaseInput :label="label" :args="args" :vertical="false" :required="required">
```
Comment (TeodoraPavlova) [inline frontend/src/components/inputs/TextareaInput.vue:2]: maybe you meant 

```suggestion
  <BaseInput :label="label" :args="args" :vertical="vertical" :required="required">
```

File: frontend/src/components/layout/BaseInput.vue [hunk 2]
```diff
@@ -1,19 +1,28 @@
...
-      <slot name="field"/>
-      <div class="text-muted text-end">
-        <small>
-          <slot name="helptext"/>
-        </small>
+      <slot name="field" />
+      <div
+        class="d-flex flex-row-reverse justify-content-between align-items-center px-1"
+      >
+        <div class="text-muted -5">
```
Comment (TeodoraPavlova) [inline frontend/src/components/layout/BaseInput.vue:20]: is there any chance that you missed a letter at the "-5"

Comment (jonas-brr) [reply frontend/src/components/layout/BaseInput.vue]: oh.. yes, just garbage left behind, thanks.

**Review by TeodoraPavlova — APPROVED** [review]

File: backend/alembic/versions/cf05edca26d8_increase_descritpion_length.py [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+# Assuming this is the correct table name and column
+def upgrade():
+    op.alter_column('attr_definitions', 'description',
+                    existing_type=sa.String(128),
+                    type_=sa.String(1000))
+
+def downgrade():
+    op.alter_column('attr_definitions', 'description',
+                    existing_type=sa.String(128),
+                    type_=sa.String(1000))
```
Comment (frozenIceage) [inline backend/alembic/versions/cf05edca26d8_increase_descritpion_length.py:26]: for downgrading the length should be changed from 1000 back to 128, right?
```suggestion
                    existing_type=sa.String(1000),
                    type_=sa.String(128))
\```

Comment (jonas-brr) [reply backend/alembic/versions/cf05edca26d8_increase_descritpion_length.py:26]: Oh.. right, good catch! :+1:

Comment (jonas-brr) [reply backend/alembic/versions/cf05edca26d8_increase_descritpion_length.py:26]: https://github.com/SUSE/aimaas/pull/225
